version: "3"
services:
  init:
    image: erlio/docker-vernemq
    environment:
    - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    ports:
    - "1883:1883"
    - "8080:8080"
    - "8888:8888"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  first:
    image: erlio/docker-vernemq
    environment:
    - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    - "DOCKER_VERNEMQ_DISCOVERY_NODE=172.16.238.10"
    networks:
      app_net:
        ipv4_address: 172.16.238.11
  second:
    image: erlio/docker-vernemq
    environment:
    - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    - "DOCKER_VERNEMQ_DISCOVERY_NODE=172.16.238.10"
    networks:
      app_net:
        ipv4_address: 172.16.238.12
  third:
    image: erlio/docker-vernemq
    environment:
    - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
    - "DOCKER_VERNEMQ_DISCOVERY_NODE=172.16.238.10"
    networks:
      app_net:
        ipv4_address: 172.16.238.13
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24